## Imports

In [129]:
# !pip install gymnasium
# !pip install imageio-ffmpeg

In [130]:
import numpy as np
import gymnasium as gym
from IPython.display import HTML
from base64 import b64encode
import imageio

## Utils

In [131]:
def record_video(env, policy, out_directory, fps=1, random_action=False, max_steps=100):
    images = []
    done = False
    truncated = False
    state, info = env.reset()
    img = env.render()
    images.append(img)
    total_reward = 0
    i = 0
    while not done and not truncated:
        i += 1
        if i > max_steps:
            break
        action = np.random.randint(4) if random_action else policy[state]
        state, reward, done, truncated, info = env.step(action)
        total_reward += reward
        img = env.render()
        images.append(img)
        if not random_action:
            print(f"action: {action}, state: {state}, reward: {reward}, done: {done}, truncated: {truncated}, info: {info}")
    imageio.mimsave(out_directory, [np.array(img) for i, img in enumerate(images)], fps=fps)
    return total_reward

In [132]:
def show_video(video_path, video_width=500):
    video_file = open(video_path, "r+b").read()
    video_url = f"data:video/mp4;base64,{b64encode(video_file).decode()}"
    return HTML(f"""<video width={video_width} controls><source src="{video_url}"></video>""")

## Random Walk

In [133]:
env = gym.make("FrozenLake-v1", map_name="4x4", is_slippery=False, render_mode='rgb_array')
total_reward = record_video(env, None, 'frozenlake_random.mp4', fps=3, random_action=True)
print(f"total reward: {total_reward}")
show_video('frozenlake_random.mp4', video_width=500)

total reward: 0.0


## Define FrozenLake MDP

In [134]:
class FrozenLakeMDP:
    def __init__(self, is_slippery):
        self.is_slippery = is_slippery
        self.terminal_states = np.zeros(16, dtype=int)
        self.terminal_states[[5, 7, 11, 12, 15]] = 1
        self.reward_fn = np.zeros(16, dtype=int)
        self.reward_fn[15] = 1

    def is_terminal(self, state):
        return self.terminal_states[state]

    def get_reward_function(self):
        return self.reward_fn

    def next_state_det(self, state, action):
        if action == 0:    # LEFT
            next_state = state - 1 if state % 4 != 0 else state
        elif action == 1:  # DOWN
            next_state = state + 4 if state // 4 != 3 else state
        elif action == 2:  # RIGHT
            next_state = state + 1 if state % 4 != 3 else state
        elif action == 3:  # UP
            next_state = state - 4 if state // 4 != 0 else state
        else:         # WRONG ACTION
            next_state = state
        return next_state

    def trans_prob(self, state, action):
        prob = np.zeros((16,), dtype=float)
        if not self.is_slippery:
            prob[self.next_state_det(state, action)] = 1.0
        else:
            prob[self.next_state_det(state, action)] += 1/3
            prob[self.next_state_det(state, (action+1)%4)] += 1/3
            prob[self.next_state_det(state, (action-1)%4)] += 1/3
        return prob

    def next_state_reward(self, state, action):
        next_state_probs = self.trans_prob(state, action)
        next_state = np.random.choice(16, p=next_state_probs)
        reward = self.reward_fn[next_state]
        return next_state, reward

In [135]:
dynamics = FrozenLakeMDP(is_slippery=False)

In [136]:
# reward function of the environent
dynamics.get_reward_function()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [137]:
# evaluating if a given state is a terminal state (= hole or goal)
print(dynamics.is_terminal(0), dynamics.is_terminal(7), dynamics.is_terminal(15))

0 1 1


In [138]:
# if we take action `a` in state `s`,
# what is the probability of landing in each state?
dynamics.trans_prob(14, 2)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])

In [139]:
# if we take action `a` in state `s`, what do we get?
# this is done through sampling the transition probability
next_state, reward = dynamics.next_state_reward(14, 2)
print(next_state, reward)

15 1


## Iterative Policy Evaluation

In [140]:
def policy_evaluation(dynamics, policy, gamma=0.9, num_iter=10):
    """
    evaluates policy based on Iterative Policy Evaluation.

    Args:
        dynamics (FrozenLakeMDP): dynamics of the environment.
        policy (numpy.array): policy we want to evaluate.
        gamma (float): discount factor.
        num_iter (int): number of iterations for the loop.

    Returns:
        numpy.array: state value function.
    """

    # TODO: implement Iterative Policy Evaluation algorithm
    state_len = 16
    action_len = 4
    s_value_function = np.zeros(16, dtype=float)
    for i in range(num_iter):
        # for all state
        for s in range(state_len):
            # we will get new state value
            new_s = 0
            a = policy[s]
            transition_prob = dynamics.trans_prob(s, a)
            next_state, reward = dynamics.next_state_reward(s, a)
            new_s += transition_prob[next_state]*(reward+gamma*s_value_function[next_state])
            if dynamics.is_terminal(s) == 1 and s != 15:
                s_value_function[s] = 0
            else:
                s_value_function[s] = new_s

    return s_value_function

In [141]:
dynamics = FrozenLakeMDP(is_slippery=False)

# 1. go-right policy
policy1 = 2 * np.ones(16, dtype=int)

# 2. shortest-path policy
policy2 = np.array([1, 2, 1, 0, 1, -1, 1, -1, 2, 1, 1, -1, -1, 2, 2, -1])

s_value_function1 = policy_evaluation(dynamics, policy1)
s_value_function2 = policy_evaluation(dynamics, policy2)

In [142]:
# TODO: print and analyze the state value function
print("State values for go-right policy:")
print(np.round(s_value_function1.reshape(4,4), 3))
print("\nState values for shortest-path policy:")
print(np.round(s_value_function2.reshape(4,4), 3))

State values for go-right policy:
[[0.    0.    0.    0.   ]
 [0.    0.    0.    0.   ]
 [0.    0.    0.    0.   ]
 [0.    5.513 6.513 6.513]]

State values for shortest-path policy:
[[2.418 3.074 3.803 3.423]
 [3.074 0.    4.613 0.   ]
 [3.803 4.613 5.513 0.   ]
 [0.    5.513 6.513 6.513]]


## Policy Iteration

In [143]:
def greedy_policy_improvement(dynamics, s_value_function, gamma=0.9):
    """
    obtains a policy in a greedy manner based on current state value function.

    Args:
        dynamics (FrozenLakeMDP): dynamics of the environment.
        s_value_function (numpy.array): state value function.
        gamma (float): discount factor.

    Returns:
        numpy.array: the greedy policy.
    """

    # TODO: implement Greedy Policy Improvement algorithm
    state_len = 16
    action_len = 4
    policy = np.random.randint(0, 4, size=16)
    for s in range(state_len):
        q_values = np.zeros(action_len)
        for a in range(action_len):
          transition_prob = dynamics.trans_prob(s, a)
          next_state, reward = dynamics.next_state_reward(s, a)
          q_values[a] += transition_prob[next_state]*(reward + gamma * s_value_function[next_state])
        policy[s] = np.argmax(q_values)

    return policy

In [144]:
def policy_iteration(dynamics, gamma=0.9, outer_iter=100, inner_iter=100):
    """
    optimizes a policy based on Policy Iteration

    Args:
        dynamics (FrozenLakeMDP): dynamics of the environment.
        gamma (float): discount factor.
        outer_iter (int): number of iterations for the Policy Iteration loop.
        inner_iter (int): number of iterations for the Policy Evaluation loop.

    Returns:
        numpy.array: the optimized policy.
    """

    # TODO: implement Policy Iteration algorithm
    state_len = 16
    action_len = 4
    s_value_function = np.zeros(state_len)
    policy = np.random.randint(0, 4, size=16)
    for i in range(outer_iter):
        old_policy = policy.copy()
        s_value_function = policy_evaluation(dynamics, policy, gamma, inner_iter)
        policy = greedy_policy_improvement(dynamics, s_value_function, gamma)
        if np.all(old_policy == policy):
            break
    return policy

In [145]:
# TODO: test and analyze the algorithm
dynamics = FrozenLakeMDP(is_slippery=False)
policy = policy_iteration(dynamics)
policy

array([1, 2, 1, 0, 1, 1, 1, 0, 2, 1, 1, 1, 2, 2, 2, 1])

In [146]:
# TODO: test the policy on the environment
env = gym.make("FrozenLake-v1", map_name="4x4", is_slippery=False, render_mode='rgb_array')
total_reward = record_video(env, policy, 'frozenlake_random.mp4', fps=5, random_action=False)
print(f"total reward: {total_reward}")
show_video('frozenlake_random.mp4', video_width=500)

action: 1, state: 4, reward: 0.0, done: False, truncated: False, info: {'prob': 1.0}
action: 1, state: 8, reward: 0.0, done: False, truncated: False, info: {'prob': 1.0}
action: 2, state: 9, reward: 0.0, done: False, truncated: False, info: {'prob': 1.0}
action: 1, state: 13, reward: 0.0, done: False, truncated: False, info: {'prob': 1.0}
action: 2, state: 14, reward: 0.0, done: False, truncated: False, info: {'prob': 1.0}
action: 2, state: 15, reward: 1.0, done: True, truncated: False, info: {'prob': 1.0}
total reward: 1.0


## Q-Learning

In [147]:
class QAgent:  # The Q-Learning RL agent

    def __init__(self, num_states, num_actions, epsilon, alpha, gamma=0.9, eps_end=0.01, eps_decay=3e-6):

        self.num_states = num_states    # number of possible states
        self.num_actions = num_actions  # number of possible actions
        self.gamma = gamma              # discount factor
        self.epsilon = epsilon          # initial exploration probability
        self.alpha = alpha              # step size
        self.eps_decay = eps_decay      # linear decay rate of epsilon
        self.eps_end = eps_end          # minimum value for epsilon
        self.q_table = np.zeros((num_states, num_actions), dtype=float)

    def choose_action(self, state):
        """
        chooses an action in an epsilon-greedy manner.

        Args:
            state (int): current state of the agent.

        Returns:
            int: the chosen action
        """

        # TODO: implement epsilon-greedy action selection
        if np.random.rand() < self.epsilon:
            action = np.random.randint(self.q_table.shape[1])
        else:
            action = np.argmax(self.q_table[state])
        return action

    def learn(self, state, action, reward, next_state):
        """
        updates the q-table based on a single interaction with the environment.

        Args:
            state (int): state of the agent.
            action (int): action chosen by the agent.
            reward (int): reward obtained by the agent.
            next_state (int): next state of the agent.
        """

        # TODO: implement Q-table update
        if state not in [5, 7, 11, 12]:
            self.q_table[state, action] = self.q_table[state, action] + \
                                          self.alpha * (reward + self.gamma * np.max(self.q_table[next_state]) - self.q_table[state, action])

        # epsilon decay
        self.epsilon = self.epsilon - self.eps_decay if self.epsilon > self.eps_end else self.eps_end

In [148]:
def train(env, agent, n_episodes=100000):
    """
        trains an agent through interactions with the environemnt using Q-learning.

        Args:
            env (gym.Env): the gym environment.
            agent (QAgent): the Q-learning agent.
            n_episodes (int): number of training episodes.
    """

    for i in range(n_episodes):
        # TODO: implement the training loop for Q-learning
        done = False
        state = env.reset()[0]
        # Until the agent reaches the goal, keep training it
        while not done:
            # Choose the action with the highest value in the current state
            action = agent.choose_action(state)
            # Implement this action and move the agent in the desired direction
            next_state, reward, done, _, _ = env.step(action)
            agent.learn(state, action, reward, next_state)
            # Update our current state
            state = next_state
        ...

In [149]:
env = gym.make("FrozenLake-v1", map_name="4x4", is_slippery=False)
agent = QAgent(num_states=16, num_actions=4, epsilon=1.0, alpha=1e-3)

In [150]:
train(env, agent)

In [151]:
# TODO: obtain the policy by a simple argmax on agent's Q-table
policy = np.argmax(agent.q_table, axis=1)
print(policy)
agent.q_table

[1 2 1 0 1 0 1 0 2 2 1 0 0 2 2 0]


array([[0.45222483, 0.59049   , 0.22271957, 0.45809321],
       [0.12258303, 0.        , 0.37222134, 0.0451762 ],
       [0.05046586, 0.57570215, 0.0123092 , 0.08970193],
       [0.08179374, 0.        , 0.00179283, 0.00221212],
       [0.50562037, 0.6561    , 0.        , 0.43798027],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.78064802, 0.        , 0.10827573],
       [0.        , 0.        , 0.        , 0.        ],
       [0.55518441, 0.        , 0.729     , 0.47961039],
       [0.52704668, 0.60538196, 0.81      , 0.        ],
       [0.59457954, 0.9       , 0.        , 0.51456359],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.21237296, 0.86935923, 0.22107769],
       [0.58865008, 0.79640706, 1.        , 0.67611839],
       [0.        , 0.        , 0.        , 0.        ]])

In [152]:
# TODO: test the policy on the environment
env = gym.make("FrozenLake-v1", map_name="4x4", is_slippery=False, render_mode='rgb_array')
total_reward = record_video(env, policy, 'frozenlake_random.mp4', fps=5, random_action=False)
print(f"total reward: {total_reward}")
show_video('frozenlake_random.mp4', video_width=500)

action: 1, state: 4, reward: 0.0, done: False, truncated: False, info: {'prob': 1.0}
action: 1, state: 8, reward: 0.0, done: False, truncated: False, info: {'prob': 1.0}
action: 2, state: 9, reward: 0.0, done: False, truncated: False, info: {'prob': 1.0}
action: 2, state: 10, reward: 0.0, done: False, truncated: False, info: {'prob': 1.0}
action: 1, state: 14, reward: 0.0, done: False, truncated: False, info: {'prob': 1.0}
action: 2, state: 15, reward: 1.0, done: True, truncated: False, info: {'prob': 1.0}
total reward: 1.0
